openapi: 3.2.0
info:
  version: 1.0.21
  title: Quality Management Speech Analytics API
  contact:
    name: QM/SA Team
    email: qm-team@8x8.com
  termsOfService: https://www.8x8.com/terms-and-conditions
  description: The Quality Management and Speech Analytics (QMSA) API enables you to access raw resources such as interaction metadata, evaluation results, and users.
servers:
- url: https://api.8x8.com/qm/{region}/{apiversion}
  description: The QM/SA API Gateway Endpoint
  variables:
    region:
      enum:
      - us-west
      - us-east
      - uk
      - ap
      - ca
      default: us-west
    apiversion:
      default: v1
security:
- bearerAuth: []
tags:
- name: Speech Analytics
paths:
  /speechAnalysis/categories/count:
    get:
      tags:
      - Speech Analytics
      summary: The Speech Analytics category count
      description: Retrieves the category count
      operationId: categories count
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '25'
              example: 25
        default:
          description: Unexpected error
      deprecated: false
  /speechAnalysis/categories:
    get:
      tags:
      - Speech Analytics
      summary: The Speech Analytics category list
      description: Retrieves the category count
      operationId: list
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: page
        in: query
        description: The page to start the query with.
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 1
      - name: size
        in: query
        description: The page size to start the query with.
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 30
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speechCategoryResponse'
              example:
                pageNumber: 1
                pageSize: 100
                pageResultSize: 1
                content:
                - categoryId: 1
                  name: Sales
                  links:
                  - rel: interactions
                    href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/1/topics?page=1&size=100
                    type: GET
                links:
                - rel: nextUrl
                  href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/categories?page=2&size=100
                  type: GET
                - rel: prevUrl
                  href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/categories?page=1&size=100
                  type: GET
        default:
          description: Unexpected error
      deprecated: false
  /speechAnalysis/{categoryId}/topics/count:
    get:
      tags:
      - Speech Analytics
      summary: The Speech Analytics topic count
      description: Retrieves the topics count within the specified category
      operationId: topics count
      parameters:
      - name: categoryId
        in: path
        description: The category unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: double
          example: 1
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '25'
              example: 25
        default:
          description: Unexpected error
      deprecated: false
  /speechAnalysis/{categoryId}/topics:
    get:
      tags:
      - Speech Analytics
      summary: The Speech Analytics topics list
      description: Retrieve the categories count
      operationId: topics list
      parameters:
      - name: categoryId
        in: path
        description: The category unique identifier
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: double
          example: 1
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: page
        in: query
        description: The page to begin the query with.
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 1
      - name: size
        in: query
        description: The page size to begin the query with.
        required: false
        style: form
        explode: true
        schema:
          type: number
          format: double
          example: 30
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/topicListResponse'
              example:
                pageNumber: 1
                pageSize: 100
                pageResultSize: 1
                content:
                - topicId: 1
                  categoryId: 1
                  name: Good agent
                  channel: AGENT_TOPICS
                  phrases:
                  - text: This is my phrase
                links:
                - rel: nextUrl
                  href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/1/topics?page=2&size=100
                  type: GET
                - rel: prevUrl
                  href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/1/topics?page=1&size=100
                  type: GET
        default:
          description: Unexpected error
      deprecated: false
components:
  schemas:
    topicListResponse:
      description: The object model for the topics definition list.
      title: Topics List Repsonse
      type: object
      properties:
        pageNumber:
          type: number
          description: The requested page number
          example: 1
        pageSize:
          type: number
          description: The requested page size
          example: 100
        pageResultSize:
          type: number
          description: The size of returned results
          example: 1
        content:
          type: array
          items:
            $ref: '#/components/schemas/topicDetailResponse'
        links:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/nextUrlLink'
            - $ref: '#/components/schemas/prevUrlLink'
      example:
        pageNumber: 1
        pageSize: 100
        pageResultSize: 1
        content:
        - topicId: 1
          categoryId: 1
          name: Good agent
          channel: AGENT_TOPICS
          phrases:
          - text: This is my phrase
        links:
        - rel: nextUrl
          href: https://api.8x8.com/qm/us-west/v1/NEXT_PAGE_REQUEST
          type: GET
        - rel: prevUrl
          href: https://api.8x8.com/qm/us-west/v1/PREV_PAGE_REQUEST
          type: GET
    speechCategoryResponse:
      description: The object model for identified speech categories
      title: Speech Categories
      type: object
      properties:
        pageNumber:
          type: number
          description: The requested page number
          example: 1
        pageSize:
          type: number
          description: The requested page size
          example: 100
        pageResultSize:
          type: number
          description: The size of the returned results
          example: 1
        content:
          type: array
          items:
            $ref: '#/components/schemas/speechCategoryContent'
        links:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/nextUrlLink'
            - $ref: '#/components/schemas/prevUrlLink'
      example:
        pageNumber: 1
        pageSize: 100
        pageResultSize: 1
        content:
        - categoryId: 1
          name: Sales
          links:
          - rel: interactions
            href: https://api.8x8.com/qm/us-west/v1/speechAnalysis/1/topics?page=1&size=100
            type: GET
        links:
        - rel: nextUrl
          href: https://api.8x8.com/qm/us-west/v1/NEXT_PAGE_REQUEST
          type: GET
        - rel: prevUrl
          href: https://api.8x8.com/qm/us-west/v1/PREV_PAGE_REQUEST
          type: GET
    topicsLink:
      description: The preformatted query URL for topics
      title: Link to Topics
      type: object
      properties:
        rel:
          type: string
          description: Relation
          example: interactions
        href:
          type: string
          description: The category topics link URL
          example: https://api.8x8.com/qm/us-west/v1/speechAnalysis/1/topics?page=1&size=100
        type:
          type: string
          description: HTTP verb
          example: GET
    speechCategoryContent:
      description: The speech category object model
      title: Speech Category Content
      type: object
      properties:
        categoryId:
          type: number
          description: The category unique identifier
          example: 1
        name:
          type: string
          description: The category name
          example: Sales
        links:
          type: array
          items:
            $ref: '#/components/schemas/topicsLink'
    nextUrlLink:
      description: The preformatted query URL for the next page
      title: Next URL Link
      type: object
      properties:
        rel:
          type: string
          description: Next link URL
          example: nextUrl
        href:
          type: string
          description: Next link URL
        type:
          type: string
          description: HTTP verb
          example: GET
    topicDetailResponse:
      description: The object model for topics detail
      title: Topic Details
      type: object
      properties:
        topicId:
          type: number
          description: The topic unique identifier
          example: 1
        categoryId:
          type: number
          description: The category unique identifier
          example: 1
        name:
          type: string
          description: The topic name
          example: Good agent
        channel:
          type: string
          description: The channel on which the topic is relevant.
          example: AGENT_TOPICS
        phrases:
          type: array
          description: The list of phrases defining the topic.
          items:
            $ref: '#/components/schemas/phrases'
    prevUrlLink:
      description: The preformatted query URL for the previous page
      title: Previous URL Link
      type: object
      properties:
        rel:
          type: string
          description: The previous link URL
          example: prevUrl
        href:
          type: string
          description: The previous link URL
        type:
          type: string
          description: HTTP verb
          example: GET
    phrases:
      description: The phrase object model
      title: Single Phrases
      type: object
      properties:
        text:
          type: string
          description: The phrase text
          example: This is my phrase
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: access_token
x-readme:
  explorer-enabled: true
  proxy-enabled: true
